# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema_branch',
            fields=[
                ('cinema_branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('cinema_branch_name', models.CharField(max_length=40)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cinema_brand',
            fields=[
                ('cinema_brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('cinema_brand_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=60)),
                ('age', models.SmallIntegerField(default=0)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='cinema_branch',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Cinema_brand'),
        ),
    ]
